name: house_rent_env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - dagshub
      - pandas==2.3.3
      - numpy==2.4.0
      - scikit-learn==1.8.0
      - matplotlib
      - seaborn
      - cloudpickle==3.1.2